# Generated by Django 3.1.1 on 2020-10-06 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date_updated',
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('other', 'Other')], default='bug', max_length=7),
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.project')),
            ],
        ),
    ]
