# Generated by Django 3.1.1 on 2020-10-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_auto_20201009_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(error_messages={'required': 'A project with this title already exists.'}, max_length=100, unique=True),
        ),
    ]
