# Generated by Django 3.1.1 on 2020-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_auto_20201013_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='num',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
