# Generated by Django 3.1.1 on 2020-10-15 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0017_auto_20201013_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_users',
            field=models.ManyToManyField(related_name='issue_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(related_name='project_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
