# Generated by Django 3.1.1 on 2020-11-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0020_auto_20201022_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='project',
        ),
        migrations.DeleteModel(
            name='IssueUser',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
