from django.urls import path
from .views import (
    ManageUsersView,
    PasswordView,
    UserCreateView,
    UserUpdateView,
    ProjectsListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectUpdateView,
    ProjectAssignView,
    ProjectIssueCreateView,
    IssueUpdateView,
    IssueCreateView,
    IssueDetailView,
    IssueAssignView,
    IssueDeleteView,
    MyIssuesView,
    CommentCreateView,
    CommentUpdateView,
    CommentDeleteView,
    ReplyCreateView,
    ReplyDeleteView,
    ReplyUpdateView,
    MyProjectsView,
    MyProfileView,
    ProfileDeleteView,
    DemoLoginView
)

app_name = 'issues'

urlpatterns = [
    path('manage-users/', ManageUsersView.as_view(), name='users-list'),
    path('create-user/', UserCreateView.as_view(), name='user-create'),
    path('<str:username>/update-user/<str:type>/', UserUpdateView.as_view(), name='user-update'),
    path('<str:username>/update-password/<str:type>/', PasswordView.as_view(), name='password-update'),
    path('projects/', ProjectsListView.as_view(), name='projects-list'),
    path('<slug:slug>/view', ProjectDetailView.as_view(), name='project-detail'),
    path('create-project/', ProjectCreateView.as_view(), name='project-create'),
    path('<slug:slug>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('<slug:slug>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('<slug:slug>/assign-users/', ProjectAssignView.as_view(), name='project-assign'),
    path('<slug:slug>/create-issue/', ProjectIssueCreateView.as_view(), name='project-issue-create'),
    path('create-issue/', IssueCreateView.as_view(), name='issue-create'),
    path('<slug:project_slug>/issue-<int:issue_num>/update/', IssueUpdateView.as_view(), name='issue-update'),
    path('<slug:project_slug>/issue-<int:issue_num>/assign/', IssueAssignView.as_view(), name='issue-assign'),
    path('<slug:project_slug>/issue-<int:issue_num>/details/', IssueDetailView.as_view(), name='issue-detail'),
    path('<slug:project_slug>/issue-<int:issue_num>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    path('<slug:project_slug>/issue-<int:issue_num>/create-comment/', CommentCreateView.as_view(), name='comment-create'),
    path('<slug:project_slug>/issue-<int:issue_num>/update-comment/', CommentUpdateView.as_view(), name='comment-update'),
    path('<slug:project_slug>/issue-<int:issue_num>/delete-comment/', CommentDeleteView.as_view(), name='comment-delete'),
    path('<slug:project_slug>/issue-<int:issue_num>/create-reply/', ReplyCreateView.as_view(), name='reply-create'),
    path('<slug:project_slug>/issue-<int:issue_num>/delete-reply/', ReplyDeleteView.as_view(), name='reply-delete'),
    path('<slug:project_slug>/issue-<int:issue_num>/update-reply/', ReplyUpdateView.as_view(), name='reply-update'),
    path('my-projects/', MyProjectsView.as_view(), name='my-projects'),
    path('my-issues/', MyIssuesView.as_view(), name='my-issues'),
    path('<str:username>/my-profile/', MyProfileView.as_view(), name='my-profile'),
    path('<str:username>/delete-profile/', ProfileDeleteView.as_view(), name='profile-delete'),
    path('demo-login/', DemoLoginView.as_view(), name='demo-login')
]
